/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "CreateTemplate": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeleteExpiredS3Objects": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeleteOrphanedS3Objects": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeleteTemplate": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DynamoDb": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ExpiredS3Objects": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "GenerateDocumentFromApiEvent": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GenerateDocumentFromSfnEvent": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetDocumentBatchResult": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetOpenApi": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetTemplate": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetTemplates": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetUrlForTemplateUpload": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SetDefaultUserPassword": {
      "name": string
      "type": "sst.aws.Function"
    }
    "StoreDocumentBatchResult": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
