/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DynamoDb": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ExpiredS3Objects": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "GetOpenApi": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
