export enum Lambda {
  createTemplate = 'create-template',
  deleteExpiredS3Objects = 'delete-expired-s3-objects',
  deleteOrphanedS3Objects = 'delete-orphaned-s3-objects',
  deleteTemplate = 'delete-template',
  generateDocumentFromApiEvent = 'generate-document-from-api-event',
  generateDocumentFromSfnEvent = 'generate-document-from-sfn-event',
  getDocumentBatchResult = 'get-document-batch-result',
  getOpenApi = 'get-open-api',
  getTemplate = 'get-template',
  getTemplates = 'get-templates',
  getUrlForTemplateUpload = 'get-url-for-template-upload',
  processMalwareScanResult = 'process-malware-scan-result',
  setDefaultUserPassword = 'set-default-user-password',
  startDocumentBatchGeneration = 'start-document-batch-generation',
  storeDocumentBatchResult = 'store-document-batch-result',
}
